# Generated by Django 5.0.1 on 2024-01-16 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='users',
            new_name='user',
        ),
    ]
